# Generated by Django 5.1.7 on 2025-03-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tiposervico',
            options={'verbose_name': 'Tipo de Serviço', 'verbose_name_plural': 'Tipos de Serviços'},
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='tipo_servico',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='tipo_servico',
            field=models.ManyToManyField(to='servico.tiposervico'),
        ),
    ]
