# Generated by Django 5.1.7 on 2025-03-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0002_alter_tiposervico_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='orcamento', max_length=20),
        ),
    ]
