# Generated by Django 5.1.7 on 2025-03-11 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0003_alter_ordemservico_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('pendente', 'PENDENTE'), ('em andamento', 'EM ANDAMENTO'), ('concluido', 'CONCLUIDO'), ('cancelado', 'CANCELADO')], default='orcamento', max_length=20),
        ),
    ]
