# Generated by Django 5.1.7 on 2025-03-11 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0004_alter_ordemservico_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('pendente', 'PENDENTE'), ('em andamento', 'EM ANDAMENTO'), ('concluido', 'CONCLUIDO'), ('cancelado', 'CANCELADO')], default='pendente', max_length=20),
        ),
        migrations.CreateModel(
            name='ImagemOrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='imagens_servico/%Y/%m/%d/')),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='servico.ordemservico')),
            ],
            options={
                'verbose_name': 'Imagem da Ordem de Serviço',
                'verbose_name_plural': 'Imagens das Ordens de Serviço',
                'ordering': ['-data_upload'],
            },
        ),
        migrations.DeleteModel(
            name='ImagemServico',
        ),
    ]
