# Generated by Django 5.1.7 on 2025-03-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0005_alter_ordemservico_status_imagemordemservico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('orcamento', 'ORÇAMENTO'), ('aprovado', 'APROVADO'), ('pendente', 'PENDENTE'), ('em andamento', 'EM ANDAMENTO'), ('concluido', 'CONCLUIDO'), ('cancelado', 'CANCELADO')], default='pendente', max_length=20),
        ),
    ]
