# Generated by Django 5.1.7 on 2025-03-25 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0006_alter_ordemservico_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(choices=[('ORCAMENTO', 'Orçamento'), ('APROVADO', 'Aprovado'), ('PENDENTE', 'Pendente'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20),
        ),
    ]
